---
- name: Get API tokenfile
  include_vars: "{{ ocp_service_account_tokenfile }}"

- name: Get Nodes
  k8s_info:
    host: "https://api.{{ cluster_address }}:6443"
    validate_certs: no
    api_key: "{{ vars[ocp_token_var] }}"
    api_version: v1
    kind: Node
  register: nodes

- name: Output Node Status
  debug:
    msg: "{{ item.metadata.name }}"
  with_items: "{{ nodes.resources }}"
...