---
- name: Get API tokenfile
  include_vars: "{{ ocp_service_account_tokenfile }}"

- name: Get Nodes
  k8s_facts:
    host: "https://api.{{ cluster_address }}:6443"
    validate_certs: no
    api_key: "{{ vars[acm_token_var] }}"
    apiVersion: v1
    kind: Node
...