---
- name: Get API tokenfile
  include_vars: "{{ ocp_service_account_tokenfile }}"

- name: login with Service Account
  ansible.builtin.command: "oc login --token={{ vars[ocp_token_var] }} --server=https://api.{{ cluster_address }}:6443"

- name: Get Node Status
  ansible.builtin.command: oc get nodes
  register: oc_nodes
  no_log: true

- name: Node Status
  debug:
    msg: "{{ oc_nodes.stdout_lines }}"

- name: Get Top Nodes
  ansible.builtin.command: oc adm top nodes
  register: oc_top_nodes
  no_log: true

- name: Node Utilization
  debug:
    msg: "{{ oc_top_nodes.stdout_lines }}"

- name: Look for nodes NOT in Ready state
  debug:
    msg:
    - "{{ item.split('   ')[0]|trim }} is not in Ready state!"
    - "  State: {{ item.split('   ')[1]|trim }}"
    - "  Node Type: {{ item.split('   ')[2]|trim }}"
  when: item|trim is not search('Ready')
  with_items: "{{ oc_nodes.stdout_lines[1:] }}"
  loop_control:
    label: "NODE NOT READY: "
...