---
- include_role:
    name: "{{ ocp_roles }}/admin_oc_login"
  vars:
    openshift_token: "{{ sa_token }}"
    openshift_username: "{{ acm_service_account_name }}"

- name: Create temporary directory for template files
  tempfile:
    state: directory
    suffix: tmp
  register: tmp_dir

- set_fact:
    working_dir: "{{ tmp_dir.path }}"

- name: Populate Templates
  template:
    src: "{{ role_path }}/templates/subscription.yaml.j2"
    dest: "{{ working_dir }}/subscription.yaml"

- name: Create App Namespace
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ app_namespace }}"

- name: Apply ACS install module repo subscription
  k8s:
    src: "{{ working_dir }}/subscription.yaml"
    state: "{{ state }}"
...