---
- name: Create Default Cluster Auth
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Set kubeconfig fact
      set_fact:
        kubefile: "{{ working_dir }}/install/{{ ocp_cluster.name }}/auth/kubeadmin-password"

    - name: Check if cluster auth is working
      ansible.builtin.command:
        argv:
          - oc
          - login
          - -u
          - kubeadmin
          - -p
          - "{{ lookup('ansible.builtin.file', kubefile) }}"
          - "https://api.{{ ocp_cluster.name }}.{{ ocp_cluster.base_domain }}:{{ k8s_port }}"
          - --insecure-skip-tls-verify
      retries: 20
      delay: 30
      register: result
      until: result.rc == 0

    - include_role:
        name: create_default_cluster_admin
      vars:
        cluster_address: "{{ ocp_cluster.name }}.{{ ocp_cluster.base_domain }}"
