---
- name: Install Pre-Requisites for OCP Playbooks
  gather_facts: false
  connection: local
  hosts: localhost
  tasks:
    - name: Download required utilities
      include_role:
        name: install_ocp_prerequisites
...
---
- name: Install Pre-Requisites for OCP Playbooks
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Download required Python modules
      pip:
        name: "{{ item }}"
      loop:
        - kubernetes
        - openshift
        - boto3

    - name: Install required collections from Ansible Galaxy
      local_action: command ansible-galaxy collection install -r files/ocp-requirements.yaml
...
