---
#################################################################################
############ Deploy OCP Cluster on AWS via IPI
#################################################################################
- name: Prepare for OCP cluster install on AWS via IPI
  hosts: localhost
  connection: local
  gather_facts: false
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws.aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws.aws_secret_access_key }}"
    AWS_REGION: "{{ aws.aws_region }}"
  tasks:
    - name: Provision OCP Cluster on AWS via IPI
      include_role:
        name: aws_provision_ocp_ipi

# TODO Check and implement?
#    - name: Set cluster_name
#      set_fact:
#        cluster_name: "{{ cluster_name }}"
#
#    - name: Set hub fact
#      set_fact:
#        cluster_type: 'hub'
#
#    - name: Store kubeadmin creds
#      include_role:
#        name: store_kubeadmin_pass