---
#################################################################################
############ Deploy OCP Cluster on AWS via IPI
#################################################################################
- name: Prepare for OCP cluster install on AWS via IPI
  hosts: localhost
  connection: local
  gather_facts: false
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws.aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws.aws_secret_access_key }}"
    AWS_REGION: "{{ aws.aws_region }}"
  tasks:
    - set_fact:
        cluster_name: "{{ ocp_cluster.name }}"
        base_domain: "{{ ocp_cluster.base_domain }}"

    - name: Provision OCP on AWS via IPI
      include_role:
        name: aws_provision_ocp_ipi