---
- set_fact:
    cluster_address: "{{ ocp_cluster.name }}.{{ ocp_cluster.base_domain }}"

- include_role:
    name: admin_oc_login

- name: Create ansible-playbook-access Namespace
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ cluster_admin_service_account_namespace }}"

- name: Create ServiceAccount
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: "{{ cluster_admin_service_account_name }}"
        namespace: "{{ cluster_admin_service_account_namespace }}"

- name: Create temporary directory for template files
  tempfile:
    state: directory
    suffix: tmp
  register: tmp_dir

- set_fact:
    working_dir: "{{ tmp_dir.path }}"

- name: Populate Templates
  template:
    src: "{{ item }}"
    dest: "{{ working_dir }}/{{ item | basename | regex_replace('\\.j2$', '') }}"
  with_fileglob:
    - ./templates/*.j2

- name: Apply Templates
  k8s:
    src: "{{ item }}"
    state: "{{ state }}"
    api_version: v1
  with_fileglob:
    - "{{ working_dir }}/*.yaml"

- name: Generate Service Account Token
  command: oc create token '{{ cluster_admin_service_account_name }}' -n '{{ cluster_admin_service_account_namespace }}'
  register: sa_token_output

- set_fact:
    sa_token: "{{ sa_token_output.stdout }}"
...