---
- name: Create ServiceAccount for ACM playbook execution and store encrypted API token
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Install ACS
      include_role:
        name: admin_create_service_account
...
